# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
TOOL_NAME    := xdpdump
XDP_TARGETS  := xdpdump_bpf xdpdump_xdp
USER_TARGETS := xdpdump
TEST_FILE    := tests/test-xdpdump.sh

LIB_DIR       = ../lib
USER_LIBS     = -lpcap
MAN_PAGE     := xdpdump.8

include $(LIB_DIR)/common.mk
