# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS := xdp_ddos.bpf tcp_ddos.bpf udp_ddos.bpf
BPF_SKEL_TARGETS := $(XDP_TARGETS)
USER_TARGETS := xdp_ddos

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
