# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := xdp_filt_ethernet xdp_filt_ip xdp_filt_udp xdp_filt_tcp xdp_filt_all
USER_TARGETS := xdp_filt_user
EXTRA_DEPS := xdp_filt_prog.h

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
