# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := xdp-trafficgen.kern

TOOL_NAME := xdp-trafficgen
USER_TARGETS := xdp-trafficgen
MAN_PAGE := xdp-trafficgen.8
EXTRA_DEPS := xdp-trafficgen.h
USER_LIBS     = -lpthread

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk

