# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS := xdp_synproxy
XDP_TARGETS := xdp_synproxy.bpf
BPF_SKEL_TARGETS := $(XDP_TARGETS)

TOOL_NAME := xdp_synproxy
LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
