#+OPTIONS: ^:nil

* Releasing and packaging a new version of xdp-tools

These are the steps needed to release a new version of xdp-tools. If any of the
steps fail, go back and fix the error, then start over from the appropriate
step.

If the fix requires changes to the sources, commit those, then rewrite the
commit made in (1.) on top of this and start over from the beginning. This
ensures that we don't end up with a whole series of package revisions just to
fix minor errors.


To release a new version of xdp-tools, follow these steps:

1. Bump version in =version.mk= and =packacing/rpm/xdp-tools.spec= -- don't
   forget a changelog entry in the latter. Commit this, bug don't tag and push
   until the rest of the steps below completed successfully.

2. Run =make archive= to generate a source tarball (xdp-tools-$VERSION.tar.gz).

3. Copy source tarball to =~/rpmbuild/SOURCES=.

4. Build local package using =rpmbuild -ba packaging/rpm/xdp-tools.spec=.

5. Check that building a scratch build on Fedora infrastructure works:
   =fedpkg scratch-build --srpm ~/rpmbuild/SRPMS/xdp-tools-$VERSION.fcXX.src.rpm=

6. Sync the xdp-tools.spec file to dist-git (but don't commit anything yet):
   - For Fedora, just copy over the new version
   - For RHEL, copy over the new version, then manually inspect the git diff and
     revert any changes specific to RHEL. This is mainly the changelog and the
     =__brp_strip= defines.

   Make sure to be on the right branch in each dist-git.

7. Create an SRPM and scratch build for RHEL (in RHEL dist-git directory):
   #+begin_src sh
   cp ~/rpmbuild/SOURCES/xdp-tools-$VERSION.tar.gz .
   rhpkg srpm
   rhpkg scratch-build --srpm xdp-tools-$VERSION.el8.src.rpm
   #+end_src

8. Upload new sources files to both Fedora and RHEL - this will also update
   the 'sources' file in each directory, which is why we didn't commit
   anything earlier:
   #+begin_src sh
   cd $FEDORA_DISTGIT_DIR
   fedpkg new-sources ~/rpmbuild/SOURCES/xdp-tools-$VERSION.tar.gz
   git add xdp-tools.spec
   git commit

   cd $RHEL_DISTGIT_DIR
   rhpkg new-sources ~/rpmbuild/SOURCES/xdp-tools-$VERSION.tar.gz
   git add xdp-tools.spec
   git commit
   #+end_src

   For both, check the git history for commit message inspiration. In
   particular, to be accepted into the RHEL dist-git, the commit message must
   reference a valid Bugzilla ID. See the commit log for earlier commits for
   syntax for this.

9. Push the dist-git repositories and request builds for each:
   #+begin_src sh
   cd $FEDORA_DISTGIT_DIR
   git push
   fedpkg build

   cd $RHEL_DISTGIT_DIR
   git push
   rhpkg build
   #+end_src

10. Tag the commit in the xdp-tools repo and push the branch and tags to github.
    Tag syntax is =v$VERSION=, where =~betaX= becomes =-betaX= (git doesn't
    allow tildes in tag names).

11. Wait for the CI gating emails to tick in. Check any failures in the CI
    dashboard and waive and/or fix as necessary. Then talk to QE to have them
    run the =manual.sst_networking.xdp-tools.tier1= tests and mark it as
    completed; this will cause the build to be tagged rhel-$VERSION-candidate (from
    rhel-$VERSION-gate) and allow it to proceed.

12. Add the new build to the errata; this may entail moving the errata status
    back to =NEW_FILES=. After adding the new build, it should be moved to QE
    state; if this is not immediately possible, just resolve any issues blocking
    it.
